from .quranPlayer import QuranPlayer
from .userGuide import UserGuide
from .researcher import Albaheth
from .book_marks import book_marcks
from .ahadeeth import hadeeth
from .brotcasts import protcasts
from .quran import Quran
from .aboutDevelopers import About_developers
from .sibha import sibha
from .namesOfAllah import NamesOfAllah
from .prayerTimes import prayer_times
from .dateConverter import DateConverter
from .athkar import Athker
from .islamicBooks import IslamicBooks
from .quranRecitations import QuranRecitations