from .genral import Genral
from .backupAndRestoart import Restoar
from .update import Update
from .tafaseer import TafaseerSettings
from .athkarSettings import AthkarSettings
from .downloadSettings import Download
from .prayerTimesSettings import PrayerTimesSettings
from .quranPlayerSettings import QuranPlayerSettings
from .locationSettings import LocationSettings